import type { Script } from './i18n/types';

/**
 * Families are generated by scripts/fonts.mjs: "Sanatan Display"/"Sanatan Text"
 * carry Latin and Devanagari; every other script has its own pair (e.g.
 * "Sanatan Display Knda") placed in front of the stack for that language only.
 */
const SUFFIX: Partial<Record<Script, string>> = {
  beng: 'Beng', guru: 'Guru', gujr: 'Gujr', orya: 'Orya', taml: 'Taml', telu: 'Telu', knda: 'Knda', mlym: 'Mlym',
};

type Role = 'display' | 'text';

const currentScript = (): Script => (document.documentElement.getAttribute('data-script') as Script | null) ?? 'latn';

function families(role: Role, script: Script): string[] {
  const base = role === 'display' ? 'Sanatan Display' : 'Sanatan Text';
  const suffix = SUFFIX[script];
  return suffix ? [`${base} ${suffix}`, base] : [base];
}

/** The display stack for text drawn on a canvas in the page's current script. */
export function canvasFontStack(script: Script = currentScript()): string {
  return `${families('display', script).map((f) => `"${f}"`).join(', ')}, Georgia, serif`;
}

/**
 * Resolves once the faces needed to draw `text` in `script` are ready, or after
 * a timeout — a slow or blocked font must never hold up a language switch or
 * the scene. Only the requested roles are fetched.
 */
export function loadFontsFor(text: string, script: Script = currentScript(), roles: readonly Role[] = ['display', 'text'], timeoutMs = 2500): Promise<void> {
  if (!('fonts' in document) || !text) return Promise.resolve();
  const requests: Promise<unknown>[] = [];
  for (const role of roles) {
    const weights = role === 'display' ? [400] : [400, 600];
    for (const family of families(role, script)) {
      for (const weight of weights) requests.push(document.fonts.load(`${weight} 16px "${family}"`, text));
    }
  }
  const timeout = new Promise<void>((resolve) => setTimeout(resolve, timeoutMs));
  return Promise.race([Promise.all(requests).then(() => undefined), timeout]).catch(() => undefined);
}
