include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - legacy/**
    - build/**
    - lib/l10n/generated/**
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_declare_return_types: true
    avoid_print: true
    prefer_final_locals: true
    unnecessary_lambdas: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
