// Builds the page's font set into src/fonts/.generated/ (git-ignored).
//
// Families
//   Sanatan Display / Sanatan Text / Sanatan Mono — Latin and Devanagari, on every page.
//   Sanatan Display Knda / Sanatan Text Knda, … — one pair per other script, put in
//     front of the stack only for elements in that language (`[lang|="kn"]`).
//   Sanatan Names — just the glyphs of each language's own name, for the language menu.
// A script's own family covering its own punctuation and joiners (ZWNJ, danda)
// is what stops a Kannada page from downloading Malayalam or Devanagari fonts.
//
// Every non-Latin face is subset (HarfBuzz keeps conjunct and matra forms) to
// the characters actually used, and its unicode-range lists exactly those
// characters. It runs before every dev server, test run and build, so new copy
// can never ask for a glyph a subset lacks.
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';

const root = fileURLToPath(new URL('..', import.meta.url));
const out = join(root, 'src/fonts/.generated');
const { LOCALES } = await import(join(root, 'src/i18n/locales.ts'));
const fontsource = (pkg) => join(root, 'node_modules/@fontsource', pkg);

/** Per script: [display package, text package, fontsource subset name]. Devanagari lives in the base families. */
const SCRIPTS = {
  deva: { display: 'tiro-devanagari-sanskrit', text: 'mukta', subset: 'devanagari' },
  beng: { display: 'tiro-bangla', text: 'noto-sans-bengali', subset: 'bengali', suffix: 'Beng' },
  guru: { display: 'tiro-gurmukhi', text: 'noto-sans-gurmukhi', subset: 'gurmukhi', suffix: 'Guru' },
  gujr: { display: 'noto-serif-gujarati', text: 'noto-sans-gujarati', subset: 'gujarati', suffix: 'Gujr' },
  orya: { display: 'noto-serif-oriya', text: 'noto-sans-oriya', subset: 'oriya', suffix: 'Orya' },
  taml: { display: 'tiro-tamil', text: 'noto-sans-tamil', subset: 'tamil', suffix: 'Taml' },
  telu: { display: 'tiro-telugu', text: 'noto-sans-telugu', subset: 'telugu', suffix: 'Telu' },
  knda: { display: 'tiro-kannada', text: 'noto-sans-kannada', subset: 'kannada', suffix: 'Knda' },
  mlym: { display: 'noto-serif-malayalam', text: 'noto-sans-malayalam', subset: 'malayalam', suffix: 'Mlym' },
};
const OM = 'ॐ';
const JOINERS = '\u200C\u200D';

async function fontsourceRange(pkg, subset, weight) {
  const css = await readFile(join(fontsource(pkg), `${weight}.css`), 'utf8');
  const match = new RegExp(`/\\* ${pkg}-${subset}-${weight}-normal \\*/[^}]*unicode-range:\\s*([^;]+);`).exec(css);
  if (!match) throw new Error(`fonts: no unicode-range for ${pkg} ${subset} ${weight}`);
  return match[1].split(',').map((part) => {
    const [lo, hi] = part.trim().replace(/^U\+/i, '').split('-').map((h) => parseInt(h, 16));
    return [lo, hi ?? lo];
  });
}

const within = (ch, ranges) => ranges.some(([lo, hi]) => ch.codePointAt(0) >= lo && ch.codePointAt(0) <= hi);

/** "U+0C95-0C97,U+0CBF" from a set of characters. */
function unicodeRange(chars) {
  const points = [...new Set([...chars].map((c) => c.codePointAt(0)))].sort((a, b) => a - b);
  const parts = [];
  for (let i = 0; i < points.length; i++) {
    let j = i;
    while (j + 1 < points.length && points[j + 1] === points[j] + 1) j++;
    const hex = (n) => n.toString(16).toUpperCase().padStart(4, '0');
    parts.push(i === j ? `U+${hex(points[i])}` : `U+${hex(points[i])}-${hex(points[j])}`);
    i = j;
  }
  return parts.join(',');
}

async function corpusText() {
  const entries = await readdir(join(root, 'src'), { withFileTypes: true, recursive: true });
  const files = [
    join(root, 'index.html'),
    ...entries.filter((e) => e.isFile() && /\.(ts|css)$/.test(e.name)).map((e) => join(e.parentPath, e.name)).filter((f) => !f.includes('.generated')),
  ];
  let text = '';
  for (const file of files) text += await readFile(file, 'utf8');
  // Resolve \uXXXX escapes written in source (the ZWNJ in the Kannada and Telugu messages).
  return { files, text: text.replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => String.fromCharCode(parseInt(hex, 16))) };
}

const { files, text: corpus } = await corpusText();
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

let css = '/* Generated by scripts/fonts.mjs — do not edit. */\n';
let bytes = 0;
let faces = 0;

async function emit(family, weight, pkg, subset, chars, fileTag) {
  // chars: null (ship the face whole), a string (subset to exactly it), or { text, range }.
  const text = chars === null || typeof chars === 'string' ? chars : chars.text;
  const rangeChars = chars === null || typeof chars === 'string' ? chars : chars.range;
  const source = await readFile(join(fontsource(pkg), 'files', `${pkg}-${subset}-${weight}-normal.woff2`));
  const name = `${family.toLowerCase().replaceAll(' ', '-')}-${weight}-${fileTag}.woff2`;
  let data = source;
  let range;
  if (chars === null) {
    range = (await fontsourceRange(pkg, subset, weight)).map(([lo, hi]) => (lo === hi ? `U+${lo.toString(16)}` : `U+${lo.toString(16)}-${hi.toString(16)}`)).join(',');
  } else {
    if (![...rangeChars].some((c) => !JOINERS.includes(c))) return;
    data = await subsetFont(source, text, { targetFormat: 'woff2' });
    range = unicodeRange(rangeChars);
  }
  await writeFile(join(out, name), data);
  bytes += data.length;
  faces++;
  css += `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('./${name}') format('woff2');\n  unicode-range: ${range};\n}\n`;
}

/**
 * Characters of the corpus a script's face must draw — without ॐ, which has a
 * face of its own — plus what the shaper needs to draw them:
 * - canonical decompositions: HarfBuzz splits two-part vowel signs (Kannada ೋ
 *   → ೆ ೂ ೕ, Tamil ொ, Malayalam ൊ, Bengali ো …) into components before
 *   shaping, so a subset without the components breaks those syllables;
 * - every combining mark in the script's blocks (vowel signs, virama, nukta),
 *   so any cluster the used letters can form still shapes.
 * The unicode-range lists the text characters and decompositions only; marks
 * never start a run of their own.
 */
async function scriptChars(pkg, subset, weight, joiners) {
  const ranges = await fontsourceRange(pkg, subset, weight);
  const used = [...new Set(corpus)].filter((c) => c !== OM && within(c, ranges) && (joiners || !JOINERS.includes(c)));
  const decomposed = used.flatMap((c) => [...c.normalize('NFD')]).filter((c) => within(c, ranges));
  const marks = [];
  for (const [lo, hi] of ranges) {
    if (hi - lo > 0x200) continue; // script blocks only, not wide punctuation ranges
    for (let cp = lo; cp <= hi; cp++) {
      const ch = String.fromCodePoint(cp);
      if (/\p{M}/u.test(ch)) marks.push(ch);
    }
  }
  return { text: [...new Set([...used, ...decomposed, ...marks])].join(''), range: [...new Set([...used, ...decomposed])].join('') };
}

// Base families: Latin as shipped, Devanagari subset, ॐ alone (declared last so it wins U+0950).
await emit('Sanatan Display', 400, 'tiro-devanagari-sanskrit', 'latin', null, 'latin');
await emit('Sanatan Display', 400, 'tiro-devanagari-sanskrit', 'devanagari', await scriptChars('tiro-devanagari-sanskrit', 'devanagari', 400, false), 'deva');
await emit('Sanatan Display', 400, 'tiro-devanagari-sanskrit', 'devanagari', OM, 'om');
for (const weight of [400, 600]) {
  await emit('Sanatan Text', weight, 'mukta', 'latin', null, 'latin');
  await emit('Sanatan Text', weight, 'mukta', 'devanagari', await scriptChars('mukta', 'devanagari', weight, false), 'deva');
}
await emit('Sanatan Mono', 500, 'ibm-plex-mono', 'latin', null, 'latin');

// One family pair per other script, covering its own joiners and punctuation.
const rules = [];
for (const [script, spec] of Object.entries(SCRIPTS)) {
  if (!spec.suffix) continue;
  const display = `Sanatan Display ${spec.suffix}`;
  const textFamily = `Sanatan Text ${spec.suffix}`;
  await emit(display, 400, spec.display, spec.subset, await scriptChars(spec.display, spec.subset, 400, true), script);
  for (const weight of [400, 600]) await emit(textFamily, weight, spec.text, spec.subset, await scriptChars(spec.text, spec.subset, weight, true), script);
  for (const locale of LOCALES.filter((l) => l.script === script)) {
    rules.push(
      `html[lang|="${locale.code}"], [lang|="${locale.code}"] {\n` +
        `  --display: '${display}', 'Sanatan Display', Georgia, serif;\n` +
        `  --body: '${textFamily}', 'Sanatan Text', system-ui, sans-serif;\n` +
        `  --mono: 'Sanatan Mono', '${textFamily}', 'Sanatan Text', ui-monospace, monospace;\n}\n`,
    );
  }
}

// The language menu: each language's own name, drawn without loading that language's full faces.
for (const [script, spec] of Object.entries(SCRIPTS)) {
  const names = LOCALES.filter((l) => l.script === script).map((l) => l.name).join('');
  await emit('Sanatan Names', 400, spec.text, spec.subset, names, script);
}

css += rules.join('');
await writeFile(join(out, 'fonts.css'), css);
console.log(`fonts: ${faces} faces, ${(bytes / 1024).toFixed(0)} KB in total (each page loads only its scripts), from ${files.length} files → ${relative(root, out)}/`);
